### ISSUE TITLE
could you share "how to or getting started" to use code.

### ISSUE THREAD

**Issue by MahmoudMabrok** [CSEMN/ShowMeTheWay#7]

**Comment by CSEMN** [comment]
app executable file(.exe) is already in releases.  
main entry point of the code is the <a href="https://github.com/CSEMN/ShowMeTheWay/blob/main/ShowMeTheWay.py">ShowMeTheWay.py </a> from the main directory.  
thanks for pointing out this issue. I'll change the readme.md file right now.
